### ISSUE TITLE
train CONTHO on InterCap

### ISSUE THREAD

**Issue by llf0223** [dqj5182/CONTHO_RELEASE#12]
Thanks for releasing this amazing work!
I downloaded RGBD_Images.zip and Res.zip, but the training shows missing mask images for human and object, how should I get these mask files to train CONTHO properly!

**Comment by dqj5182** [comment]
Thank you for your interest in our work!

As the InterCap dataset itself was not initially introduced by our paper, we could not release data of the dataset.
But due to large volume of requests for the masks to conduct fair comparison, we provide link for InterCap masks that we have used for our official manuscript.

Note that the masks were provided by InterCap at the time of our publication.

Link for the InterCap masks: [Google Drive](https://drive.google.com/file/d/1EWcOl4BSxT1r9jcuwiWuiTsy_fxZGp9g/view?usp=sharing)

**Comment by llf0223** [comment]
Thanks for your help!
